apiVersion: v2
name: fullstack-app
description: Fullstack application (Frontend + Backend + MySQL) deployed using Helm and ArgoCD
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: Vinay M
    email: vinay@example.com
