apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.mysql.name }}
    environment: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
      protocol: TCP
