apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.mysql.name }}
    environment: {{ .Values.global.environment }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
        environment: {{ .Values.global.environment }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.auth.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.auth.password }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: {{ .Values.mysql.resources.requests.cpu }}
              memory: {{ .Values.mysql.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mysql.resources.limits.cpu }}
              memory: {{ .Values.mysql.resources.limits.memory }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
